# # GitLab CI in conjunction with GitLab Runner can use Docker Engine to test and build any application.
# # Docker, when used with GitLab CI, runs each job in a separate and isolated container using the predefined image that is set up in .gitlab-ci.yml.
# image: nexus.engageska-portugal.pt/ska-docker/tango-builder:latest

# services:
# - docker:dind

# # During the development of software, there can be many stages until it's ready for public consumption.
# # You sure want to first test your code and then deploy it in a testing or staging environment before you release it to the public.
# # That way you can prevent bugs not only in your software, but in the deployment process as well.
# # See also https://docs.gitlab.com/ee/ci/environments.html
# stages:
# - build_0
# - build_1
# - build_2
# - build_3
# - build_4
# - build_5
# - test

# # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#authenticating-to-the-container-registry
# before_script:
#   - docker login -u $DOCKER_REGISTRY_USER_LOGIN -p $CI_REGISTRY_PASS_LOGIN $CI_REGISTRY

# build_tango-builder:
#   retry: 2
#   stage: build_0
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/tango-builder
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     - master
#   only:
#     changes:
#     - docker/tango/tango-builder/**/*

# build_dependencies:
#   retry: 2
#   stage: build_1
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/tango-dependencies
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     - master
#   only:
#     changes:
#     - docker/tango/tango-dependencies/**/*

# build_tango-db:
#   retry: 2
#   stage: build_1
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/tango-db
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     - master
#   only:
#     changes:
#     - docker/tango/tango-db/**/*

# build_tango-cpp:
#   retry: 2
#   stage: build_2
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/tango-cpp
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     - master
#   only:
#     changes:
#     - docker/tango/tango-dependencies/**/*
#     - docker/tango/tango-cpp/**/*

# build_tango-java:
#   retry: 2
#   stage: build_2
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/tango-java
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     - master
#   only:
#     changes:
#     - docker/tango/tango-dependencies/**/*
#     - docker/tango/tango-java/**/*

# build_tango-dsconfig:
#   retry: 2
#   stage: build_3
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/tango-dsconfig
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     changes:
#     - docker/tango/tango-dependencies/**/*
#     - docker/tango/tango-cpp/**/*
#     - docker/tango/tango-dsconfig/**/*

# build_ska-python-buildenv:
#   retry: 2
#   stage: build_3
#   tags:
#     - docker-executor
#   script:
#     - cd docker/tango/ska-python-buildenv
#     - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#     - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     changes:
#       - docker/tango/tango-dependencies/**/*
#       - docker/tango/tango-cpp/**/*
#       - docker/tango/ska-python-buildenv/**/*

# build_ska-python-runtime:
#   retry: 2
#   stage: build_4
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/ska-python-runtime
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     changes:
#     - docker/tango/tango-dependencies/**/*
#     - docker/tango/tango-cpp/**/*
#     - docker/tango/ska-python-buildenv/**/*
#     - docker/tango/ska-python-runtime/**/*

# build_tango-rest:
#   retry: 2
#   stage: build_3
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/tango-rest
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     changes:
#     - docker/tango/tango-dependencies/**/*
#     - docker/tango/tango-cpp/**/*
#     - docker/tango/tango-rest/**/*

# build_tango-itango:
#   retry: 2
#   stage: build_5
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/tango-itango
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     changes:
#     - docker/tango/tango-dependencies/**/*
#     - docker/tango/tango-cpp/**/*
#     - docker/tango/ska-python-buildenv/**/*
#     - docker/tango/ska-python-runtime/**/*
#     - docker/tango/tango-itango/**/*

# build_tango-pogo:
#   retry: 2
#   stage: build_3
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/tango-pogo
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     changes:
#     - docker/tango/tango-dependencies/**/*
#     - docker/tango/tango-java/**/*
#     - docker/tango/tango-pogo/**/*

# build_tango-starter:
#   retry: 2
#   stage: build_3
#   tags:
#   - docker-executor
#   script:
#   - cd docker/tango/tango-starter
#   - make DOCKER_BUILD_ARGS="--no-cache" DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST build
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST push
#   only:
#     changes:
#     - docker/tango/tango-dependencies/**/*
#     - docker/tango/tango-cpp/**/*
#     - docker/tango/tango-starter/**/*

# test-framework-tango-itango:
#   retry: 2
#   stage: test
#   tags:
#   - docker-executor
#   script:
#   - mkdir .public
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST -C docker/tango/tango-itango pull > .public/pull.txt
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST -C docker/tango/tango-itango test > .public/result.txt
#   - mv .public public
#   artifacts:
#     paths:
#     - public
#   # only:
#     # changes:
#     # - docker/tango/tango-dependencies/**/*
#     # - docker/tango/tango-cpp/**/*
#     # - docker/tango/tango-python/**/*
#     # - docker/tango/tango-itango/**/*

# test-framework-tango-rest:
#   retry: 2
#   stage: test
#   tags:
#   - docker-executor
#   script:
#   - mkdir .public
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST -C docker/tango/tango-rest test > .public/result.txt
#   - mv .public public
#   artifacts:
#     paths:
#     - public
#   # only:
#     # changes:
#     # - docker/tango/tango-dependencies/**/*
#     # - docker/tango/tango-cpp/**/*
#     # - docker/tango/tango-rest/**/*

# test-framework-ska-python-buildenv:
#   retry: 2
#   stage: test
#   tags:
#   - docker-executor
#   script:
#   - mkdir .public
#   - make DOCKER_REGISTRY_USER=$DOCKER_REGISTRY_USER DOCKER_REGISTRY_HOST=$DOCKER_REGISTRY_HOST -C docker/tango/ska-python-buildenv test > .public/result.txt
#   - mv .public public
#   artifacts:
#     paths:
#     - public
#   # only:
#     # changes:
#     # - docker/tango/tango-dependencies/**/*
#     # - docker/tango/tango-cpp/**/*
#     # - docker/tango/ska-python-buildenv/**/*
